name: voicetext
description: VoiceText Web API library for Dart-lang.
version: 1.0.0
homepage: https://github.com/aoisensi/voicetext.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
